@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

title Filter origin server components

' container itself
Container_Boundary(webext, "Filter origin server") {
  ' core  
  Component(parser, "Filter parser", "Python (subscriptionParser.py)", "Filter parsing utils")
  Component(validator, "Filter validator", "Python", "Automated filter checks")
  ComponentDb(fileSystem, "File system", "", "Templates, full filter lists, diffs")
  Component(combiner, "Combiner", "Python (combineSubscriptions.py)", "Filter list templating")
  Component(diffGenerator, "Diff generator", "Python (?)", "Filter list diff generator")
}

Container(compressor, "7z", "Executable")
Container(cvs, "hg/git", "Executable")

Container_Boundary(host, "Host N") {
  Container_Ext(syncScript, "Synchronizing script", "?", "Run by Cron")
  ComponentDb_Ext(fileSystemHost, "File system", "", "")
  Container_Ext(httpServer, "HTTP server", "Apache", "Serves the filter lists (full/diff)")
  Container_Ext(analytics, "Analytics", "", "Set of scripts and tools")
}

' external container
ContainerDb_Ext(repo, "Public filter rules repositories", "Mercurial/Git")
Container_Ext(webExt, "Web extension", "JavaScript", "As a part of desktop browser")

' relations
Rel_D(parser, cvs, "Uses")
Rel_L(parser, repo, "Fetches the changes from")
Rel_R(parser, validator, "Validates filters")
Rel_R(validator, combiner, "Send the filters")
Rel_U(combiner, fileSystem, "Uses templates stored in")
Rel_D(combiner, compressor, "Uses")
Rel_U(combiner, fileSystem, "Puts full filter lists to")
Rel_D(diffGenerator, fileSystem, "Gets full filter lists from, puts diff filter lists to")
Rel_L(syncScript, fileSystem, "Fetches the filter updates", "rsync")
Rel_D(syncScript, fileSystemHost, "Stores the filter updates in")
Rel_U(httpServer, fileSystemHost, "Serves the filter updates from")
Rel_U(httpServer, fileSystemHost, "Saves requests logs to")
Rel_L(analytics, fileSystemHost, "Loads and parses requests logs from")
Rel_U(webExt, httpServer, "Requests filter updates", "HTTP")
@enduml