@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

LAYOUT_WITH_LEGEND()
title Context diagram

' persons
Person(user, "User", "Desktop users")
Person(coreDevs, "WebExt Core/SDK developers")
Person(webExtDevs, "WebExt developers")
Person(snippetDevs, "Snippets/ML developers")
Person(filterDevs, "Filter developers")
Person(ops, "Operations developers")
Person_Ext(filterAuthors, "Filter authors")
Person_Ext(chromeStoreModerators, "Chrome store moderators")

' system itself
System(browser, "Desktop browser")
Container(webExt, "Web extension", "JavaScript", "Ad blocking web extension")
System(backEnd, "Filters back-end", "Filter subscriptions back-end")

' ext systems
System_Ext(chromeStore, "Chrome store")
System_Ext(websiteHosting, "Websites hosting", "Hosts the websites")
ContainerDb_Ext(gitRepo, "Public filter rules repositories", "Git")

' relations
Rel_R(user, browser, "Searches a web extension, initiates a navigation")
Rel_U(browser, websiteHosting, "Navigates to web sites", "HTTP")
Rel_R(coreDevs, webExtDevs, "Provide web extension SDK")
Rel_U(snippetDevs, webExtDevs, "Provide snippets and ML model and lib")
Rel_U(webExtDevs, chromeStore, "Publish to")
Rel_R(webExtDevs, webExt, "Develop")
Rel_D(browser, chromeStore, "Installs a web extension from")
Rel_R(chromeStore, webExt, "Hosts")
Rel_D(browser, webExt, "Has installed")
Rel_U(chromeStoreModerators, webExt, "Review")
Rel(chromeStoreModerators, chromeStore, "Approve to")
Rel_U(filterDevs, backEnd, "Develop")
Rel_U(ops, backEnd, "Develop and maintain")
Rel_U(filterAuthors, gitRepo, "Publish subscriptions updates to")
Rel_R(browser, backEnd, "Requests subscriptions updates from", "HTTP")
Rel_R(backEnd, gitRepo, "Fetches the changes from", "Git")
@enduml