@startuml

actor User as user
participant Browser as browser
database    "WebExt Store" as store
participant "Web extension" as webext
participant "ServiceWorker script" as swScript
boundary "Alert API" as schedulerApi
boundary "Content Filtering API" as cfApi
boundary "Messaging API" as messagingApi

user -> browser : Type search query 
browser -> store : Search 
return Search results
browser --> user : Show search results
user -> browser : Click "Install"
browser -> store : Download
return Web extension bundle
browser -> browser : Install web extension
browser -> webext : Initialize
group Initialization
    webext -> swScript : Execute
    swScript -> swScript : Choose subscriptions
    swScript -> cfApi : Add static rules from the bundle
    swScript -> schedulerApi : Schedule subscriptions update
    swScript -> messagingApi : Subscribe to messages from Content script(s)
end

@enduml