@startuml
actor       User            as user
participant Browser         as browser
database    "Chrome Store"  as store
participant "Web extension" as webext
participant "Background script" as bgScript
boundary "Alert API"     as schedulerApi
boundary "Content Filtering API" as cfApi
boundary "Messaging API" as messagingApi

user -> browser : Type search query 
browser -> store : Search 
return Search results
browser --> user : Search results
user -> browser : Click "Install"
browser -> store : Download
return Web extension bundle
browser -> browser : Install web extension
browser -> webext : Initialize
group Initialization
    webext -> bgScript : Execute
    bgScript -> bgScript : Choose subscriptions
    bgScript -> cfApi : Add static rules from the bundle
    bgScript -> schedulerApi : Schedule subscriptions update
    bgScript -> messagingApi : Subscribe to messages from Content script(s)
end

@enduml