@startuml
actor       User            as user
participant Browser         as browser
database    "Chrome Store"  as store
participant "Web extension" as webext
participant "Background script" as bg
boundary "Alert API"     as schedulerApi
boundary "Content Filtering API" as cfApi
boundary "Messaging API" as messagingApi
user -> browser : Type search query 
browser -> store : Search 
store -> browser : Search results
browser -> user : Search results
user -> browser : Click "Install"
browser -> store : Download
store -> browser : Web extension bundle
browser -> browser : Install web extension
browser -> webext : Initialize
group Initialization
    webext -> bg : Execute
    bg -> bg : Choose subscriptions
    bg -> cfApi : Add static rules from the bundle
    bg -> schedulerApi : Schedule subscriptions update
    bg -> messagingApi : Subscribe to messages from Content script(s)
end
@enduml