@startuml

boundary "Alert API" as schedulerApi
boundary "Content Filtering API" as cfApi
boundary "Persistence API" as persistenceApi
participant "ServiceWorker script" as swScript
participant "Back-end" as backEnd

schedulerApi -> swScript : Signal
swScript -> persistenceApi : Load index and subscriptions
return Index and subscriptions
swScript -> backEnd : Download subscription (full and/or diff)
return Subscription data
swScript -> swScript : Update Index
swScript -> cfApi : Update dynamic rules
swScript -> persistenceApi : Save Index and subscriptions

@enduml